controllers-films-users first version
KukushkinIgorA/java-filmorate pull request #1
Opened 2022-11-02 07:48 UTC by KukushkinIgorA

Sprint 9 first version

2022-11-02 19:55 UTC, EvgenyKoptubenko commented on pom.xml
> +			<groupId>org.zalando</groupId>
Для чего эта зависимость? Без нее проект компилируется и запускается и проходят тесты

2022-11-02 19:57 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Film createFilm(Film film) {
Не знаю рассказывали или нет. но попробуй создание и хранение фильмов вынести в сервисы.
"Если есть желание и рассказывали как это сделать"

2022-11-02 20:04 UTC, EvgenyKoptubenko requested changes
Есть небольшое предложение попробовать вынести создание и хранение объектов в отдельные сервисы, если об этом рассказывали.
Если нет, то присылай - работа сделана хорошо.

2022-11-07 05:49 UTC, KukushkinIgorA commented
> Есть небольшое предложение попробовать вынести создание и хранение объектов в отдельные сервисы, если об этом рассказывали. Если нет, то присылай - работа сделана хорошо.

В этом спринте про сервисы не было, думаю будет в следующем, там и сделаю.

2022-11-07 19:05 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2022-11-08 05:45 UTC, merged