Add database
KukushkinIgorA/java-filmorate pull request #4
Opened 2022-12-13 17:06 UTC by KukushkinIgorA

2022-12-14 10:11 UTC, EvgenyKoptubenko commented on src/main/resources/data.sql
> +-- INSERT INTO GENRE (GENRE_ID, NAME) VALUES (1, 'Комедия') ON CONFLICT DO NOTHING;
Все-таки, если это нужно для тестирования, то должен быть тогда отдельный файл с тестовыми данными. Не должно быть такого, что нужно раскомментировать, руками добавлять

2022-12-14 10:23 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
Тесты есть, но не все контроллеры покрыты тестами. Тесты оооочень важная составляющая разработки. Если есть желание, сделай побольше тестов.
Еще попробуй, если есть желание, сделать юнит тесты контроллеров с использованием mockmvc или еще какой-то технологии. Т.е. тестироваться должен не сам класс, а словно ты вызываешь контроллер как пользователь

2022-12-14 10:40 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +public class UserDbStorage implements UserStorage {
У User должен быть полный CRUD, т.е. должно быть удаление

2022-12-14 10:42 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Если есть желание, то лучше вынести LikeDbStorage, FriendDbStorage в отдельные классы

2022-12-14 10:44 UTC, EvgenyKoptubenko commented on src/main/resources/schema.sql
> +    user_friend_id integer generated always as identity
В каждой таблице, которая создана для связи много ко многим, точно ли нужно создавать отдельный идентификатор? Для чего этот отдельный Primary Key?

2022-12-14 10:44 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Почти нет замечаний. Если есть желание, попробуй изменить тесты.

2022-12-17 17:41 UTC, KukushkinIgorA commented on src/main/resources/data.sql
> +-- INSERT INTO GENRE (GENRE_ID, NAME) VALUES (1, 'Комедия') ON CONFLICT DO NOTHING;
Тут не приходится удалять руками, вариант с merge работает и с тестами и при запуске приложения. Удалил закомментированную чась.

2022-12-17 17:42 UTC, KukushkinIgorA commented on src/test/java/ru/yandex/practicum/filmorate/FilmoRateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
Сделал тесты на все контроллеры + на контроллере фильмов потренировался c @Mock

2022-12-17 17:42 UTC, KukushkinIgorA commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDbStorage.java
> +public class UserDbStorage implements UserStorage {
По тз не было задания реализовать удаления сущностей юзера и фильма. Уточнил у наставника, это задание будет в рамках группового проекта

2022-12-17 17:43 UTC, KukushkinIgorA commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Не добрался

2022-12-17 17:43 UTC, KukushkinIgorA commented on src/main/resources/schema.sql
> +    user_friend_id integer generated always as identity
На самом деле в данном случае можно обойтись и без него, я сделал это по привычке, т.к. раньше работал с Sebel CRM и там в оракловой бд все таблицы создавались с синтетическим ключем, независимо от того таблица пересечений это или еще какая.

2022-12-17 18:17 UTC, EvgenyKoptubenko approved these changes
Работа сделана очень хорошо. Спасибо.

2022-12-18 13:04 UTC, merged